name: PR Title

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  lint:
    name: Conventional Commits
    runs-on: ubuntu-latest
    if: github.event.action != 'edited' || github.event.changes.title != null
    permissions:
      pull-requests: read
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            perf
            build
            ci
            revert
            test
            style
